name: PR Labelling

on:
  pull_request:
    branches: [main]
    types: [opened]
  pull_request_target:
    types: [opened]

  workflow_dispatch:

jobs:
  assign-label-to-pr:
    name: Assign Labels to PR
    runs-on: ubuntu-latest

    steps:
      - uses: codelytv/pr-size-labeler@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          xs_max_size: "10"
          s_max_size: "100"
          m_max_size: "500"
          l_max_size: "1000"
          fail_if_xl: "false"

      - uses: actions/labeler@v3
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          configuration-path: .github/workflows/configs/labeler-config.yml

      # Adds labels based on branch type
      - uses: TimonVS/pr-labeler-action@v3
        with:
          configuration-path: ".github/workflows/configs/pr-title-branch-labeler.yml"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: kentaro-m/auto-assign-action@v1.2.1
        with:
          configuration-path: ".github/workflows/configs/assignment-config.yml" # Only needed if you use something other than .github/auto_assign.yml
